version: '3.8'

services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"

  api_gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - ride_request_service
      - dispatcher_service

  ride_request_service:
    build: ./services/ride_request_service
    ports:
      - "8001:8001"

  dispatcher_service:
    build: ./services/dispatcher_service
    ports:
      - "8002:8002"
    depends_on:
      - taxi_service
      - rabbitmq

  taxi_service:
    build: ./services/taxi_service
    ports:
      - "8003:8003"
    depends_on:
      - redis

  simulation_service:
    build: ./services/simulation_service
    depends_on:
      - api_gateway
