version: '3.8'

services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  ride_service:
    build:
      context: .
      dockerfile: ./services/ride_service/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  taxi_service:
    build:
      context: .
      dockerfile: ./services/taxi_service/Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      redis:
        condition: service_healthy

  dispatcher_service:
    build:
      context: .
      dockerfile: ./services/dispatcher_service/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      rabbitmq:
        condition: service_healthy
      taxi_service:
        condition: service_started
      redis:
        condition: service_healthy

  nginx:
    image: nginx:latest
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
    depends_on:
      ride_service:
        condition: service_started
      taxi_service:
        condition: service_started
      dispatcher_service:
        condition: service_started

  simulation_service:
    build:
      context: .
      dockerfile: ./services/simulation_service/Dockerfile
    depends_on:
      nginx:
        condition: service_started
