version: '3.8'

services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"

  ride_service:
    build: ./services/ride_service
    ports:
      - "8001:8001"
    depends_on:
      - redis

  taxi_service:
    build: ./services/taxi_service
    ports:
      - "8003:8003"
    depends_on:
      - redis

  dispatcher_service:
    build: ./services/dispatcher_service
    ports:
      - "8002:8002"
    depends_on:
      - taxi_service
      - rabbitmq

  nginx:
    image: nginx:latest
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
    depends_on:
      - ride_service
      - taxi_service
      - dispatcher_service

  simulation_service:
    build: ./services/simulation_service
    depends_on:
      - nginx
